"""Render the repo's config.yml (the single bundle input) from the harness Config, for a given mode. So the
tester fills ONE file (config.env) and never hand-edits config.yml; the product bundle reads config.yml
natively via its `include`.

App-runtime-config note: this app is BUNDLE-MANAGED — its command + env come from the DAB app `config` block
(resources.apps.aia_app in databricks.yml), applied by `bundle run aia_app`. A bare `databricks apps start`
re-snapshots WITHOUT that env (crashes: KeyError 'AIA_CATALOG'), so the supported RESTART is
`bundle run aia_app`, not bare apps stop/start.
"""
from __future__ import annotations

from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
JOB_MODES = ("job", "job_warehouse")


def render(cfg, mode: str, out_path: str | Path | None = None) -> Path:
    """Write config.yml for `mode` from `cfg` (a harness Config) and return the path. The SAME renderer emits
    a stage block or a prod block depending on cfg.bundle_target, so multi-env runs share this one path."""
    out = Path(out_path) if out_path else (_REPO_ROOT / "config.yml")
    target = cfg.bundle_target or "stage"
    lines = [
        "# GENERATED by tests/harness/render_config.py from $AIA_CONFIG — do not hand-edit.",
        "targets:",
        f"  {target}:",
        "    variables:",
        f'      catalog: "{cfg.get("CATALOG")}"',
        f'      schema: "{cfg.get("SCHEMA")}"',
        f'      warehouse_id: "{cfg.get("WAREHOUSE_ID")}"',
        f'      lakebase_project: "{cfg.get("LAKEBASE_PROJECT")}"',
        f'      pg_database: "{cfg.get("PG_DATABASE")}"',
        f'      app_name: "{cfg.get("APP_NAME")}"',
        # LLM gateway: plain URL + token from AWS Secrets Manager via a UC service credential (lib/llm.py).
        f'      llm_endpoint_url: "{cfg.get("AIA_LLM_ENDPOINT_URL")}"',
        f'      llm_service_credential: "{cfg.get("AIA_LLM_SERVICE_CREDENTIAL")}"',
        f'      llm_secret_arn: "{cfg.get("AIA_LLM_SECRET_ARN")}"',
        f'      llm_secret_region: "{cfg.get("AIA_LLM_SECRET_REGION", "us-west-2")}"',
        f'      llm_secret_json_key: "{cfg.get("AIA_LLM_SECRET_JSON_KEY", "token")}"',
        f'      agent_mode: "{mode}"',
    ]
    # Both job variants run the investigate job as the job SP and need the run_as overlay.
    if mode in JOB_MODES:
        job_sp = cfg.get("JOB_SP")
        lines += [
            f'      job_sp: "{job_sp}"',
            # JOB mode: overlay the investigate job's run_as as a TARGET-SCOPED override (a second top-level
            # `resources` block keyed `investigate` collides with databricks.yml — "multiple resources with
            # the same key"; a target override MERGES onto the base instead). in_process omits it, so DAB
            # defaults run_as to the deploying identity (that mode never triggers the job).
            #
            # NOTE: the job SP (run_as) also needs CAN_READ on the deployed notebook — granted POST-DEPLOY in
            # scripts/setup.py, NOT here: a target-level bundle `permissions` block is AUTHORITATIVE over the
            # deployed resources, so it RESETS the investigate job's ACL on every deploy and would wipe the
            # app SP's CAN_MANAGE_RUN. Keeping ALL job-mode ACLs as post-deploy grants avoids that clobber.
            "    resources:",
            "      jobs:",
            "        investigate:",
            "          run_as:",
            f'            service_principal_name: "{job_sp}"',
        ]
    out.write_text("\n".join(lines) + "\n")
    return out
